apiVersion: v1
kind: Pod
metadata: 
  name: nginx-labels
  labels: #lables
    project: roboshop
    purpose: labels
    environment: dev
    app: nginx

spec: 
  containers: 
  - name: nginx
    image: nginx