apiVersion: v1
kind: Pod
metadata:
  name: annotation
  labels:
    project: roboshop
    environment: dev
  annotations: #annotations
    description: "This pod is created to demonstrate pod annotations"
    jenkisUrl: "https://jenkins.com/roboshop/build" 

spec:
  containers:
  - name: nginx
    image: nginx
