apiVersion: v1
kind: Pod #kind as pod
metadata: 
  name: nginx-env

spec: 
  containers: 
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "K8s"
    - name: DURATIONS
      value: "120hrs"