apiVersion: v1
kind: Pod #kind as pod
metadata: 
  name: nginx-configmaps

spec: 
  containers: 
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: configmaps #calling from 08-config-map.yaml file

