apiVersion: v1
kind: Pod #kind as pod
metadata: 
  name: nginx-secrets

spec: 
  containers: 
  - name: nginx
    image: nginx
    envFrom: 
    - secretRef:
        name: secrets #calling from 10-secrets.yaml file
