apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    purpose: replicaset-practice
    project: roboshop
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      purpose: replicaset-demo
      tier: frontend
      project: roboshop
  template:
    metadata:
      labels:
        purpose: replicaset-demo
        tier: frontend
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
