apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    purpose: deployment-practice
    project: roboshop
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      purpose: deployment-demo
      tier: frontend
      project: roboshop
  template:
    metadata:
      labels:
        purpose: deployment-demo
        tier: frontend
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
