apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::493652701259:role/eksctl-doctor-nodegroup-doctor-NodeInstanceRole-Wp3FZDTeotpv
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - devops
      userarn: arn:aws:iam::493652701259:user/sagar
      username: sagar
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T06:01:09Z"
  name: aws-auth
  namespace: kube-system
  uid: 0708e6eb-644f-47de-ad49-7a0a40b65d61
