apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: doctor
  name: doctor-trainee
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "sagar" to read pods in the "doctor" namespace.
# You need to already have a Role named "doctor-trainee" in that namespace.
kind: RoleBinding
metadata:
  name: doctor-trainee
  namespace: doctor
subjects:
# You can specify more than one "subject"
- kind: User
  name: sagar # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: doctor-trainee # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io



# cluster level reource access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: pvc-reader
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["persistentvolumes", "namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: pvc-reader
subjects:
- kind: User
  name: sagar # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pvc-reader
  apiGroup: rbac.authorization.k8s.io
