apiVersion: v1
kind: Service
metadata:
  name: nginx-service-np
  labels:
    project: practice
    module: test

spec: 
  type: LoadBalancer
  selector:
    # this service will attaches with pod: labels
    project: practice
    env: dev
    module: k8s-resources
  ports:
  - protocol: TCP
    port: 80 # service port which you want to expose
    targetPort: 80 # container port