apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: doctor
  region: us-east-1

managedNodeGroups:
  - name: doctor
    instanceTypes: ["m7i-flex.large"] #  "m5a.large", "c5.large", "t3.large","m5.large"
    desiredCapacity: 2
    # spot: true